[package]
name = "rad-common"
version = "0.1.0"
edition = "2018"
license = "GPL-3.0-or-later"

[features]
default = []
ethereum = ["ethers", "coins-bip32", "async-trait", "hex"]

[dependencies]
anyhow = "1.0"
base64 = "0.13"
byteorder = "1.4"
either = { version = "1.6" }
git-repository = "0.14"
git2 = "0.13"
lazy_static = "1.4.0"
serde_json = "1.0"
serde = "1.0"
lexopt = "0.2"
librad = { version = "0" }
rad-clib = { version = "0" }
rad-profile = { version = "0" }
rad-identities = { version = "0" }
rad-terminal = { path = "../terminal" }
radicle-git-ext = { version = "0" }
url = { version = "2" }
sha2 = { version = "0.10.2" }
ureq = { version = "2.2", default-features = false, features = ["json", "tls"] }
thiserror = "1"

# Ethereum feature dependencies

[dependencies.ethers]
version = "0.6.2"
default-features = false
features = ["ledger"]
optional = true

[dependencies.coins-bip32]
version = "0.6.0"
optional = true

[dependencies.async-trait]
version = "0.1.51"
optional = true

[dependencies.hex]
version = "0.4.3"
optional = true
