[package]
name = "rad-sync"
version = "0.1.0"
authors = ["The Radicle Team <dev@radicle.xyz>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Synchronize radicle projects with seeds"

[dependencies]
anyhow = "1.0"
fastrand = "1.6"
lexopt = { version = "0.2" }
librad = "0"
lnk-clib = "0"
lnk-profile = "0"
rad-common = { path = "../common" }
rad-terminal = { path = "../terminal" }
url = { version = "*" }
